include:
  - copy_dir_aprel
  - copy_dir_soft
  - copy_dir_sysadmin
  - copy_dir_starter
  - config_lgpo
  - config_restore
  - config_firewall
  - remove_appx
  - install_vnc
  - install_drvfr
  - install_net
  - delete_files
