include:
  - copy_dir_aprel
  - copy_dir_soft
  - copy_dir_xeclient
  - copy_dir_sysadmin
  - copy_dir_starter
  - gpedit
  - powershell
  - remove_appx
  - install_net
  - install_vnc
  - regedit_env